local Encounter1 = {
    name="Encounter1",
    path="/server/assets/ezlibs-assets/ezencounters/ezencounters.zip",
    weight=10,
    enemies={
        {name="Mettaur",rank=1},
        {name="Spikey",rank=1},
        {name="Cannodumb (family)",rank=1},
        {name="KillerEye",rank=1},
        {name="DemonEye",rank=1},
        {name="JokerEye",rank=1},
        {name="Fishy",rank=1},
        {name="Metrid",rank=1},
        {name="Basher",rank=1},
        {name="Ratty",rank=1},
        {name="Yort",rank=1},
        {name="Volcano",rank=1},
        {name="Swordy",rank=1},
        {name="Scuttle",rank=1},
        {name="Scutz",rank=1},
        {name="Scuttler",rank=1},
        {name="Scuttzer",rank=1},
    },
    obstacles={
        {name="IceCube"},
    },
    positions={
        {1,2,3,15,16,17},
        {4,0,5,12,13,14},
        {6,7,8,9,10,11},
    },
    obstacle_positions={
        {0,0,0,0,0,0},
        {0,0,0,0,0,0},
        {0,0,0,0,0,0},
    },
    player_positions={
        {0,0,0,0,0,0},
        {0,1,0,0,0,0},
        {0,0,0,0,0,0},
    },
    tiles={
        {1,1,1,1,1,1},
        {1,1,1,1,1,1},
        {1,1,1,1,1,1},
    },
    teams={
        {2,2,2,1,1,1},
        {2,2,2,1,1,1},
        {2,2,2,1,1,1},
    },
}

local Encounter2 = {
    name="Encounter2",
    path="/server/assets/ezlibs-assets/ezencounters/ezencounters.zip",
    weight=10,
    enemies={
        {name="Scuttlest",rank=1},
        {name="Dominerd",rank=1},
        {name="WindBox",rank=1},
        {name="VacuumFan",rank=1},
        {name="Bunny",rank=1},
        {name="TuffBunny",rank=1},
        {name="MegaBunny",rank=1},
        {name="Shrimpy",rank=1},
        {name="HardHead",rank=1},
        {name="HotHead",rank=1},
        {name="ColdHead",rank=1},
        {name="Boomer",rank=1},
        {name="Gloomer",rank=1},
        {name="Doomer",rank=1},
        {name="Quaker",rank=1},
    },
    obstacles={
    },
    positions={
        {1,7,0,14,15,0},
        {6,0,5,11,12,13},
        {2,3,4,8,9,10},
    },
    obstacle_positions={
        {0,0,0,0,0,0},
        {0,0,0,0,0,0},
        {0,0,0,0,0,0},
    },
    player_positions={
        {0,0,0,0,0,0},
        {0,1,0,0,0,0},
        {0,0,0,0,0,0},
    },
    tiles={
        {1,1,1,1,1,1},
        {1,1,1,1,1,1},
        {1,1,1,1,1,1},
    },
    teams={
        {2,2,2,1,1,1},
        {2,2,2,1,1,1},
        {2,2,2,1,1,1},
    },
}

return {
    minimum_steps_before_encounter=80,
    encounter_chance_per_step=0.05,
    encounters={Encounter1,Encounter2}
}